"""NoInternet group enforcement — blocks WAN access for assigned devices.

Uses a firewall include script that creates a ``hash:mac`` ipset
(``fvpn_noint_macs``) and a single iptables REJECT rule in FORWARD
matching the ipset + WAN output device.  This covers ALL zones without
needing per-zone rules.

fw3 on OpenWrt 21.02 cannot create ``hash:mac`` ipsets from UCI, so
we manage the ipset and iptables rules directly via a firewall include
script (re-applied on every ``firewall reload``).

MAC membership is persisted in ``/etc/fvpn/noint.macs`` on the router.
The kernel ipset is also updated directly for immediate effect.

Execution model:
  1. Collect MACs of devices assigned to NoInternet profiles.
  2. Diff against the live kernel ipset membership.
  3. Apply adds/removes via ``ipset add/del`` (immediate, no reload).
  4. Write ``.macs`` file for persistence across reboots.
  5. Ensure the include script is deployed and registered with fw3.
"""

from typing import Optional

import persistence.profile_store as profile_store
from consts import PROFILE_TYPE_NO_INTERNET


NOINT_IPSET = "fvpn_noint_macs"
_MACS_FILE = "/etc/fvpn/noint.macs"
_SCRIPT_PATH = "/etc/fvpn/noint_rules.sh"
_UCI_INCLUDE = "fvpn_noint_include"
_CHAIN = "FVPN_NOINT"

# Legacy names — detected and migrated on first sync
_LEGACY_IPSET = "fvpn_noint_ips"
_LEGACY_RULE = "fvpn_noint_block"
_LEGACY_UCI_IPSET = "fvpn_noint_macs"  # old UCI ipset section
# Legacy per-zone rules from earlier attempt
_LEGACY_RULE_PREFIX = "fvpn_noint_"

_SCRIPT_CONTENT = r"""#!/bin/sh
# Auto-generated by Flint VPN Manager — NoInternet block rules
# Re-applied on every firewall reload

MACS_FILE="%(macs_file)s"
IPSET="%(ipset)s"
CHAIN="%(chain)s"

# Create ipset (hash:mac for dual-stack IPv4+IPv6)
ipset create "$IPSET" hash:mac -exist

# Populate from .macs file (source of truth across reboots)
ipset flush "$IPSET"
[ -f "$MACS_FILE" ] && while IFS= read -r mac; do
    [ -n "$mac" ] && ipset add "$IPSET" "$mac" -exist
done < "$MACS_FILE" || true

# Create/flush REJECT chain
iptables -N "$CHAIN" 2>/dev/null
iptables -F "$CHAIN"

# Discover WAN output device
wan_dev=$(uci get network.wan.device 2>/dev/null || echo "eth1")

# REJECT WAN-bound traffic from NoInternet MACs
iptables -A "$CHAIN" -m set --match-set "$IPSET" src -o "$wan_dev" \
    -j REJECT --reject-with icmp-port-unreachable

# Insert in FORWARD chain (idempotent)
iptables -C FORWARD -j "$CHAIN" 2>/dev/null || \
    iptables -I FORWARD 1 -j "$CHAIN"
""" % {"macs_file": _MACS_FILE, "ipset": NOINT_IPSET, "chain": _CHAIN}


def sync_noint_to_router(
    router,
    store: Optional[dict] = None,
) -> dict:
    """Reconcile the NoInternet ipset on the router with local intent.

    Args:
        router: RouterAPI instance
        store: profile_store dict (loaded if None)

    Returns:
        {"applied": bool, "reload": bool, "adds": int, "removes": int}
    """
    if store is None:
        store = profile_store.load()

    # Clean up legacy UCI sections (one-time migration)
    _migrate_legacy(router)

    profiles = {p["id"]: p for p in store.get("profiles", [])}
    noint_pids = {
        pid for pid, p in profiles.items()
        if p.get("type") == PROFILE_TYPE_NO_INTERNET
    }

    assignments = store.get("device_assignments", {})

    desired_macs = set()
    for mac, pid in assignments.items():
        if pid in noint_pids:
            desired_macs.add(mac.upper())

    # Read live kernel ipset membership
    try:
        live_macs = {m.upper() for m in router.ipset_tool.members(NOINT_IPSET)}
    except Exception:
        live_macs = set()

    add = sorted(desired_macs - live_macs)
    remove = sorted(live_macs - desired_macs)
    applied = False
    needs_reload = False

    if not noint_pids and not desired_macs:
        # No NoInternet groups — tear down if anything exists
        if _include_exists(router) or live_macs:
            _remove_include(router)
            return {"applied": True, "reload": True, "adds": 0, "removes": len(live_macs)}
        return {"applied": False, "reload": False, "adds": 0, "removes": 0}

    # Ensure the include script is deployed
    if not _include_exists(router):
        _deploy_include(router)
        # Create kernel ipset and populate from desired state
        router.ipset_tool.create(NOINT_IPSET, "hash:mac")
        if desired_macs:
            router.ipset_tool.membership_batch(
                NOINT_IPSET, add=sorted(desired_macs))
        _write_macs_file(router, desired_macs)
        # Reload to execute the include script (creates iptables rules)
        router.service_ctl.reload("firewall")
        needs_reload = True
        applied = True
        add = []
        remove = []
    else:
        # Include exists — ensure kernel ipset is live
        router.ipset_tool.create(NOINT_IPSET, "hash:mac")

    # Apply membership diff (immediate kernel effect, no reload)
    if add or remove:
        try:
            router.ipset_tool.membership_batch(NOINT_IPSET, add=add, remove=remove)
            applied = True
        except Exception:
            pass
        # Persist to .macs file for next firewall reload
        _write_macs_file(router, desired_macs)

    return {
        "applied": applied,
        "reload": needs_reload,
        "adds": len(add),
        "removes": len(remove),
    }


# ── Include script management ─────────────────────────────────────────


def _include_exists(router) -> bool:
    """Check if the noint firewall include is registered."""
    try:
        val = router.uci.get(f"firewall.{_UCI_INCLUDE}", "MISSING").strip()
        return val != "MISSING"
    except Exception:
        return False


def _deploy_include(router) -> None:
    """Write the include script and register it with fw3."""
    router.exec(f"mkdir -p /etc/fvpn")
    router.write_file(_SCRIPT_PATH, _SCRIPT_CONTENT)
    router.exec(f"chmod +x {_SCRIPT_PATH}")
    router.uci.ensure_firewall_include(_UCI_INCLUDE, _SCRIPT_PATH)


def _remove_include(router) -> None:
    """Remove the include script, .macs file, ipset, and UCI registration."""
    try:
        router.uci.delete(f"firewall.{_UCI_INCLUDE}")
        router.uci.commit("firewall")
    except Exception:
        pass
    router.exec(f"rm -f {_SCRIPT_PATH} {_MACS_FILE}")
    router.ipset_tool.destroy(NOINT_IPSET)
    # Flush the iptables chain on reload
    router.service_ctl.reload("firewall")


def _write_macs_file(router, macs: set) -> None:
    """Write the .macs file to the router (one MAC per line)."""
    content = "\n".join(sorted(macs)) + "\n" if macs else ""
    router.write_file(_MACS_FILE, content)


# ── Migration ─────────────────────────────────────────────────────────


def _migrate_legacy(router) -> None:
    """Remove all legacy UCI sections (hash:ip ipset, single rule, per-zone rules, UCI ipset)."""
    dirty = False

    # Legacy hash:ip ipset
    for name in (_LEGACY_IPSET, _LEGACY_UCI_IPSET):
        try:
            if router.uci.get(f"firewall.{name}", "MISSING").strip() != "MISSING":
                router.uci.delete(f"firewall.{name}")
                dirty = True
        except Exception:
            pass

    # Legacy single rule (fvpn_noint_block)
    try:
        if router.uci.get(f"firewall.{_LEGACY_RULE}", "MISSING").strip() != "MISSING":
            router.uci.delete(f"firewall.{_LEGACY_RULE}")
            dirty = True
    except Exception:
        pass

    # Legacy per-zone rules (fvpn_noint_{zone})
    try:
        firewall = router.uci.show("firewall")
        for section, fields in firewall.items():
            if fields.get("_type") != "rule":
                continue
            if section.startswith(_LEGACY_RULE_PREFIX) and section != _LEGACY_RULE:
                try:
                    router.uci.delete(f"firewall.{section}")
                    dirty = True
                except Exception:
                    pass
    except Exception:
        pass

    if dirty:
        try:
            router.uci.commit("firewall")
        except Exception:
            pass

    # Clean up legacy kernel ipsets
    try:
        router.ipset_tool.destroy(_LEGACY_IPSET)
    except Exception:
        pass


# ── Wipe ──────────────────────────────────────────────────────────────


def wipe_noint(router) -> None:
    """Remove all NoInternet state from the router."""
    _remove_include(router)
    _migrate_legacy(router)
