/** Emoji data with searchable keywords per emoji.
 *  Format: [emoji, "keyword1 keyword2 ..."]
 */
const _e = (emoji, kw) => ({ e: emoji, k: kw });

export const EMOJI_CATEGORIES = [
  { name: 'Security', emojis: [
    _e('🔒','lock locked secure private vpn'),_e('🔐','lock key secure password'),_e('🛡️','shield protect guard firewall'),
    _e('🔑','key access login auth'),_e('🗝️','key old vintage'),_e('🚫','forbidden blocked banned no'),
    _e('⛔','stop blocked no entry'),_e('🚷','no pedestrians restricted'),_e('🔓','unlock open unlocked'),_e('🛑','stop halt'),
    _e('👁️','eye watch surveillance monitor'),_e('🕵️','detective spy investigate'),_e('🧱','wall brick block firewall'),
  ]},
  { name: 'Devices', emojis: [
    _e('📱','phone mobile smartphone'),_e('💻','laptop computer notebook'),_e('🖥️','desktop monitor screen pc'),
    _e('⌨️','keyboard type input'),_e('🖨️','printer print'),_e('📷','camera photo'),_e('🎧','headphones audio music'),
    _e('📡','antenna satellite dish signal'),_e('🔌','plug power electric'),_e('💾','floppy disk save'),
    _e('📻','radio'),_e('📞','phone telephone call'),_e('📟','pager'),_e('🖲️','trackball mouse'),
    _e('💿','cd disc'),_e('📀','dvd disc'),_e('🔋','battery power charge'),_e('⏰','clock alarm timer'),
    _e('📺','tv television screen monitor'),_e('🕹️','joystick controller gaming'),
    _e('🎙️','microphone mic podcast studio'),_e('📹','video camera camcorder'),_e('🖱️','mouse click computer'),
    _e('💽','minidisc'),_e('🧲','magnet'),_e('🪫','low battery empty'),
  ]},
  { name: 'Network', emojis: [
    _e('🌐','globe internet web world network'),_e('🌍','earth africa europe globe'),_e('🌎','earth americas globe'),
    _e('🌏','earth asia globe'),_e('📶','signal wifi bars wireless'),_e('🛰️','satellite space orbit'),
    _e('📨','email message incoming'),_e('📧','email message mail'),_e('📬','mailbox inbox'),
    _e('📤','upload outbox send'),_e('📥','download inbox receive'),_e('🔗','link chain url'),
    _e('⚡','lightning fast speed bolt'),_e('🚀','rocket fast launch speed'),_e('💡','bulb idea light'),
    _e('🔄','refresh sync reload arrows'),_e('↗️','arrow up right outgoing'),_e('↙️','arrow down left incoming'),
    _e('🌡️','thermometer temperature hot cold'),
  ]},
  { name: 'People', emojis: [
    _e('👤','person user profile'),_e('👥','people group team users'),_e('👨‍👩‍👧‍👦','family'),
    _e('👨‍💻','man technologist developer coder'),_e('👩‍💻','woman technologist developer coder'),_e('🧑‍💻','person technologist developer'),
    _e('👶','baby child infant'),_e('🧒','child kid'),_e('🧑','person adult'),_e('👨','man'),_e('👩','woman'),
    _e('🧓','older person elder'),_e('👴','old man grandpa'),_e('👵','old woman grandma'),
    _e('🤖','robot bot android ai'),_e('👻','ghost spooky'),_e('👾','alien monster space invader game'),
    _e('🧑‍🎓','student school'),_e('🧑‍🔧','mechanic repair'),_e('🧑‍🍳','chef cook kitchen'),
    _e('👷','construction worker builder'),_e('🦸','superhero hero'),_e('🧙','wizard mage magic'),
  ]},
  { name: 'Places', emojis: [
    _e('🏠','house home'),_e('🏡','house garden home'),_e('🏢','office building work'),_e('🏣','post office'),
    _e('🏥','hospital medical'),_e('🏦','bank money finance'),_e('🏫','school education'),_e('🏭','factory industrial'),
    _e('🏰','castle medieval'),_e('🏯','japanese castle'),_e('⛪','church religion'),_e('🕌','mosque'),
    _e('🕍','synagogue'),_e('🗽','statue liberty usa'),_e('🏗️','construction building'),_e('🏪','store shop convenience'),
    _e('🏬','department store mall'),_e('🏨','hotel'),_e('🏩','love hotel'),_e('🏟️','stadium arena'),
  ]},
  { name: 'Transport', emojis: [
    _e('✈️','airplane plane travel flight'),_e('🚗','car auto vehicle'),_e('🏍️','motorcycle bike'),_e('🚲','bicycle bike'),
    _e('⛵','sailboat boat'),_e('🚂','train locomotive'),_e('🚁','helicopter'),_e('🛸','ufo flying saucer'),
    _e('🚌','bus'),_e('🚎','trolleybus'),_e('🚑','ambulance'),_e('🚒','fire truck engine'),
    _e('🚓','police car'),_e('🚕','taxi cab'),_e('🏎️','racing car fast'),_e('🛵','scooter'),
    _e('🛴','kick scooter'),_e('🚢','ship boat cruise'),_e('⛽','fuel gas petrol'),_e('🛤️','railway track'),
  ]},
  { name: 'Activities', emojis: [
    _e('🎮','gaming controller game play'),_e('🎬','movie film cinema clapper'),_e('🎵','music note song'),
    _e('🎸','guitar music rock'),_e('🎹','piano keyboard music'),_e('🎨','art paint palette'),
    _e('📚','books reading study library'),_e('🎯','target bullseye dart goal'),_e('🎲','dice game random'),
    _e('♟️','chess strategy'),_e('🏋️','gym weights fitness workout'),_e('🧘','yoga meditation'),
    _e('⚽','soccer football'),_e('🏀','basketball'),_e('🎾','tennis'),_e('🏈','american football'),
    _e('⚾','baseball'),_e('🎳','bowling'),_e('🏓','ping pong table tennis'),_e('🥊','boxing'),
  ]},
  { name: 'Work', emojis: [
    _e('💼','briefcase business work office'),_e('🎓','graduation education school'),_e('🔧','wrench tool fix repair'),
    _e('⚙️','gear settings config'),_e('🛠️','tools hammer wrench'),_e('🧪','lab test experiment science'),
    _e('📂','folder file directory'),_e('🗂️','card index dividers organize'),_e('📝','memo note write'),
    _e('📊','chart bar graph stats'),_e('📈','chart growth up trending'),_e('📉','chart down declining'),
    _e('📋','clipboard list checklist'),_e('📌','pin pushpin'),_e('📎','paperclip attach'),
    _e('🖊️','pen write'),_e('✏️','pencil edit write'),_e('📐','triangle ruler'),_e('📏','ruler measure'),_e('🗑️','trash delete recycle bin'),
  ]},
  { name: 'Nature', emojis: [
    _e('🌳','tree deciduous'),_e('🌴','palm tree tropical'),_e('🌵','cactus desert'),_e('🌺','flower hibiscus'),
    _e('🌻','sunflower'),_e('🌹','rose flower red'),_e('🍀','clover luck four leaf'),_e('🍁','maple leaf autumn fall'),
    _e('🌙','moon crescent night'),_e('⭐','star'),_e('☀️','sun sunny bright'),_e('🌈','rainbow'),
    _e('❄️','snowflake cold winter ice'),_e('🔥','fire hot flame'),_e('💧','water drop droplet'),
    _e('🌊','wave ocean sea water'),_e('⛰️','mountain'),_e('🏔️','snow mountain'),_e('🌋','volcano'),_e('🏝️','island tropical beach'),
  ]},
  { name: 'Food', emojis: [
    _e('☕','coffee tea hot drink'),_e('🍕','pizza'),_e('🍔','hamburger burger'),_e('🍟','fries french'),
    _e('🌮','taco mexican'),_e('🍣','sushi japanese'),_e('🍜','noodles ramen'),_e('🍩','donut doughnut'),
    _e('🍪','cookie biscuit'),_e('🎂','cake birthday'),_e('🍰','shortcake dessert'),_e('🍫','chocolate bar candy'),
    _e('🍿','popcorn movie'),_e('🥤','cup straw drink'),_e('🍺','beer mug drink'),_e('🍷','wine glass drink'),
    _e('🧁','cupcake'),_e('🥐','croissant pastry'),_e('🥯','bagel bread'),_e('🧇','waffle'),
  ]},
  { name: 'Animals', emojis: [
    _e('🐶','dog puppy'),_e('🐱','cat kitten'),_e('🐭','mouse'),_e('🐰','rabbit bunny'),_e('🦊','fox'),
    _e('🐻','bear'),_e('🐼','panda'),_e('🐨','koala'),_e('🐯','tiger'),_e('🦁','lion'),
    _e('🐮','cow'),_e('🐷','pig'),_e('🐸','frog'),_e('🐵','monkey'),_e('🐔','chicken'),
    _e('🐧','penguin'),_e('🐦','bird'),_e('🦅','eagle'),_e('🐺','wolf'),_e('🐝','bee honeybee'),
  ]},
  { name: 'Symbols', emojis: [
    _e('❓','question mark help'),_e('❔','question mark white'),_e('❗','exclamation important'),_e('❕','exclamation white'),
    _e('⚠️','warning caution alert triangle'),_e('🚨','alarm siren emergency red'),_e('⁉️','exclamation question interrobang'),
    _e('‼️','double exclamation important urgent'),_e('✅','check yes done ok'),_e('❌','cross no wrong delete'),
    _e('💯','hundred perfect score'),_e('🆘','sos help emergency'),_e('🔔','bell notification alert'),_e('🔕','bell mute silent'),
    _e('📢','loudspeaker announcement'),_e('📣','megaphone announce'),
    _e('❤️','heart red love'),_e('💚','green heart'),_e('💙','blue heart'),_e('💜','purple heart'),
    _e('🧡','orange heart'),_e('💛','yellow heart'),_e('🤍','white heart'),_e('🖤','black heart'),
    _e('🔴','red circle'),_e('🟢','green circle'),_e('🔵','blue circle'),_e('🟡','yellow circle'),
    _e('🟣','purple circle'),_e('🟠','orange circle'),_e('⚪','white circle'),_e('⚫','black circle'),
    _e('🟤','brown circle'),_e('🔶','orange diamond large'),_e('🔷','blue diamond large'),_e('🔸','orange diamond small'),
    _e('🔹','blue diamond small'),_e('▶️','play right arrow'),_e('⏸️','pause'),_e('⏹️','stop square'),
    _e('♻️','recycle green'),_e('💤','sleep zzz'),_e('💬','speech bubble chat message'),_e('💭','thought bubble think'),
    _e('🏷️','tag label'),_e('🔖','bookmark'),_e('🪧','placard sign'),_e('🚩','flag red alert'),
    _e('🏁','checkered flag finish race'),_e('🎌','crossed flags japan'),_e('🏴','black flag'),_e('🏳️','white flag surrender'),
    _e('♾️','infinity forever loop'),_e('💠','diamond dot cute'),_e('🔱','trident emblem'),_e('⚜️','fleur de lis'),
    _e('ℹ️','info information'),_e('Ⓜ️','metro m circle'),_e('🅿️','parking p'),_e('🆗','ok button'),
  ]},
];
